### ISSUE TITLE
AoT build fails when using forRoot / forChild methods

### ISSUE THREAD

**Issue by koodikindral** [Greentube/localize-router#8]
**app-routing.module.ts:**
```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { LocalizeRouterModule } from 'localize-router/localize-router';

export const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' }
];
@NgModule({
  imports: [
    LocalizeRouterModule.forRoot(routes),
    RouterModule.forRoot(routes)
  ],
  exports: [LocalizeRouterModule, RouterModule]
})
export class AppRoutingModule { }
```

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppRoutingModule in C:/Projects/frontend/dist/tmp/app/app-routing.module.ts, resolving symbol AppRoutingModule in C:/Projects/frontend/dist/tmp/app/app-routing.module.ts
    at simplifyInContext (C:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:537:15)
    at StaticReflector.simplify (C:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:541:20)
    at StaticReflector.annotations (C:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:93:28)
    at NgModuleResolver.resolve (C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (C:\Projects\frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
Compilation failed
```

**Comment by koodikindral** [comment]
Hi,
Any ideas what might cause it?

**Comment by meeroslav** [comment]
Hi, sorry for waiting.

This error usually means you are using anonymous function in the module intialization.
Instead you should use exported function. 
I haven't seen your TranslateModule initialized. Do you have something like this in your AppModule:
```
export function createTranslateLoader(http: Http) {
  return new TranslateStaticLoader(http, '/assets/locales', '.json');
}

TranslateModule.forRoot({
    provide: TranslateLoader,
    useFactory: (createTranslateLoader),
    deps: [Http]
})
```

You can try to find more information on [#11262](https://github.com/angular/angular/issues/11262).
If that doesn't help can you provide minimal project where this error happens?

**Comment by koodikindral** [comment]
Hi, ng2-translate is being initialized in a following way:

```
export function createTranslateLoader(http: Http) {
  return new TranslateStaticLoader(http, './assets/i18n', '.json');
}
...
@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    AppRoutingModule,
    AboutModule,
    HomeModule,
    SharedModule.forRoot(),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    })],
  declarations: [AppComponent],
...
```

This is not causing any problems. I will also try to provide a minimal example.

**Comment by koodikindral** [comment]
Could it be that LocalizeRouterModule.forRoot() and LocalizeRouterModule.forChild() invoke:

```
export function initializeLocalizeRouterFactory(routes: Routes) {
  return (loader: LocalizeParser) => () => loader.load(routes);
}
```

which contains lambdas?

**Comment by meeroslav** [comment]
@koodikindral You are right. However solution is not trivial, that's why it's taking so long.

**Comment by koodikindral** [comment]
4ca42d51c9c546e25378708c5cde1d6a73c95868 - is still work in progress? I can help to test it once ready

**Comment by meeroslav** [comment]
Unfortunately it's still in progress, the original problem was fixed but now compiler mis-compiles `localize-router` and tries to locate LocalizeParser in non-existing folder.

This is the current error, in case you get it:
```
ERROR in ./src/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve '../../localize-router.service' in '/Users/Miro/Code/universal-localize-example/src/app'
```

The origin comes from broken `app.module.ngfactory`:
```
...
import * as import68 from '../../localize-router.service';
...
if ((token === import68.LocalizeParser)) { return this._LocalizeParser_61; }
...
get _LocalizeParser_61():any {
  if ((this.__LocalizeParser_61 == null)) { (this.__LocalizeParser_61 = import1.localizeLoaderFactory(this._TranslateService_46,this._Http_42)); }
  return this.__LocalizeParser_61;
}
```

**Comment by meeroslav** [comment]
It works ok if you move/copy `LocalizeParser` provider factory to `app.module`. Please refer to readme for more details or look at [https://github.com/meeroslav/universal-localize-example](https://github.com/meeroslav/universal-localize-example).

Seems that 4ca42d51c9c546e25378708c5cde1d6a73c95868 fixed it.

I will have to follow up with Angular core team why moving this factory to app.module was necessary.

**Comment by koodikindral** [comment]
Works perfectly! Thanks a lot!
